var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1i864aa._.js")
R.c("server/chunks/ssr/0z49_next_dist_esm_build_templates_app-page_0g8jqjx.js")
R.c("server/chunks/ssr/[root-of-the-server]__16cvm25._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1w-xwfh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mrtssz._.js")
R.c("server/chunks/ssr/_1x7g02w._.js")
R.c("server/chunks/ssr/apps_web_src_125qyu9._.js")
R.c("server/chunks/ssr/0z49_next_dist_client_components_1wcqmza._.js")
R.c("server/chunks/ssr/0z49_next_dist_client_components_builtin_forbidden_17ia1a-.js")
R.c("server/chunks/ssr/0z49_next_dist_client_components_builtin_unauthorized_0riv0fw.js")
R.c("server/chunks/ssr/0z49_next_dist_client_components_builtin_global-error_12vnnj_.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_page_actions_1agtzgh.js")
R.m(48096)
module.exports=R.m(48096).exports
