packages:
  - apps/web
  - packages/*

onlyBuiltDependencies:
  - sharp
allowBuilds:
  '@playwright/browser-chromium': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
storeDir: /Users/jason/Desktop/pc/agenttest/.pnpm-store/v11
