packages:
  - apps/web
  - packages/*

onlyBuiltDependencies:
  - sharp
allowBuilds:
  '@playwright/browser-chromium': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  sharp: true
  unrs-resolver: true
storeDir: /Users/jason/Desktop/pc/agenttest/.pnpm-store/v11
