var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(platform)/settings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-en7wp._.js")
R.c("server/chunks/ssr/0z49_next_dist_0qgx69i._.js")
R.c("server/chunks/ssr/0z49_next_dist_esm_build_templates_app-page_0z4vch-.js")
R.c("server/chunks/ssr/[root-of-the-server]__16cvm25._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1w-xwfh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mrtssz._.js")
R.c("server/chunks/ssr/_1x7g02w._.js")
R.c("server/chunks/ssr/apps_web_src_125qyu9._.js")
R.c("server/chunks/ssr/0z49_next_dist_client_components_1wcqmza._.js")
R.c("server/chunks/ssr/0z49_next_dist_client_components_builtin_forbidden_17ia1a-.js")
R.c("server/chunks/ssr/0z49_next_dist_client_components_builtin_unauthorized_0riv0fw.js")
R.c("server/chunks/ssr/0z49_next_dist_client_components_builtin_global-error_12vnnj_.js")
R.c("server/chunks/ssr/apps_web_src_1mwzctc._.js")
R.c("server/chunks/ssr/apps_web_src_20ohk5k._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_(platform)_settings_page_actions_1k5xx3z.js")
R.m(61743)
module.exports=R.m(61743).exports
