// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/docs" | "/docs/shortcuts" | "/docs/test-cases" | "/docs/tutorials" | "/feedback" | "/login" | "/profile" | "/projects" | "/projects/[projectId]/agents" | "/projects/[projectId]/agents/[agentId]" | "/projects/[projectId]/browser-profiles" | "/projects/[projectId]/datasets" | "/projects/[projectId]/datasets/[datasetId]" | "/projects/[projectId]/environments" | "/projects/[projectId]/experiments" | "/projects/[projectId]/gates" | "/projects/[projectId]/models" | "/projects/[projectId]/overview" | "/projects/[projectId]/reviews" | "/projects/[projectId]/runs" | "/projects/[projectId]/runs/[runId]" | "/projects/[projectId]/scorers" | "/projects/[projectId]/security" | "/projects/[projectId]/test-agent" | "/projects/[projectId]/test-plans" | "/projects/[projectId]/test-plans/[planId]" | "/settings" | "/system/users"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/docs": {}
  "/docs/shortcuts": {}
  "/docs/test-cases": {}
  "/docs/tutorials": {}
  "/feedback": {}
  "/login": {}
  "/profile": {}
  "/projects": {}
  "/projects/[projectId]/agents": { "projectId": string; }
  "/projects/[projectId]/agents/[agentId]": { "projectId": string; "agentId": string; }
  "/projects/[projectId]/browser-profiles": { "projectId": string; }
  "/projects/[projectId]/datasets": { "projectId": string; }
  "/projects/[projectId]/datasets/[datasetId]": { "projectId": string; "datasetId": string; }
  "/projects/[projectId]/environments": { "projectId": string; }
  "/projects/[projectId]/experiments": { "projectId": string; }
  "/projects/[projectId]/gates": { "projectId": string; }
  "/projects/[projectId]/models": { "projectId": string; }
  "/projects/[projectId]/overview": { "projectId": string; }
  "/projects/[projectId]/reviews": { "projectId": string; }
  "/projects/[projectId]/runs": { "projectId": string; }
  "/projects/[projectId]/runs/[runId]": { "projectId": string; "runId": string; }
  "/projects/[projectId]/scorers": { "projectId": string; }
  "/projects/[projectId]/security": { "projectId": string; }
  "/projects/[projectId]/test-agent": { "projectId": string; }
  "/projects/[projectId]/test-plans": { "projectId": string; }
  "/projects/[projectId]/test-plans/[planId]": { "projectId": string; "planId": string; }
  "/settings": {}
  "/system/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
