// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../../../../../../src/app/(account)/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(account)/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(help)/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(help)/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(help)/docs/shortcuts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/shortcuts">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(help)/docs/shortcuts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(help)/docs/test-cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/test-cases">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(help)/docs/test-cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(help)/docs/tutorials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/tutorials">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(help)/docs/tutorials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(help)/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(help)/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/agents/[agentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/agents/[agentId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/agents/[agentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/agents">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/browser-profiles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/browser-profiles">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/browser-profiles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/datasets/[datasetId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/datasets/[datasetId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/datasets/[datasetId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/datasets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/datasets">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/datasets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/environments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/environments">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/environments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/experiments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/experiments">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/experiments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/gates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/gates">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/gates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/models">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/overview">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/reviews">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/runs/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/runs/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/runs">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/scorers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/scorers">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/scorers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/security">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/test-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/test-agent">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/test-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/test-plans/[planId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/test-plans/[planId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/test-plans/[planId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/[projectId]/test-plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/test-plans">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/[projectId]/test-plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/system/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system/users">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/system/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../../../../../../src/app/(account)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(account)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(help)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(help)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(platform)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(platform)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
