// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AddCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPostData,
  AddCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPostErrors,
  AddCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPostResponses,
  AddMemberApiV1ProjectsProjectIdMembersPostData,
  AddMemberApiV1ProjectsProjectIdMembersPostErrors,
  AddMemberApiV1ProjectsProjectIdMembersPostResponses,
  ApplyResultApiV1ProjectsProjectIdRunsRunIdResultPostData,
  ApplyResultApiV1ProjectsProjectIdRunsRunIdResultPostErrors,
  ApplyResultApiV1ProjectsProjectIdRunsRunIdResultPostResponses,
  ArchiveProjectApiV1ProjectsProjectIdArchivePostData,
  ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors,
  ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses,
  CancelRunApiV1ProjectsProjectIdRunsRunIdCancelPostData,
  CancelRunApiV1ProjectsProjectIdRunsRunIdCancelPostErrors,
  CancelRunApiV1ProjectsProjectIdRunsRunIdCancelPostResponses,
  CreateAgentApiV1ProjectsProjectIdAgentsPostData,
  CreateAgentApiV1ProjectsProjectIdAgentsPostErrors,
  CreateAgentApiV1ProjectsProjectIdAgentsPostResponses,
  CreateDatasetApiV1ProjectsProjectIdDatasetsPostData,
  CreateDatasetApiV1ProjectsProjectIdDatasetsPostErrors,
  CreateDatasetApiV1ProjectsProjectIdDatasetsPostResponses,
  CreatePlanApiV1ProjectsProjectIdTestPlansPostData,
  CreatePlanApiV1ProjectsProjectIdTestPlansPostErrors,
  CreatePlanApiV1ProjectsProjectIdTestPlansPostResponses,
  CreateProjectApiV1ProjectsPostData,
  CreateProjectApiV1ProjectsPostErrors,
  CreateProjectApiV1ProjectsPostResponses,
  CreateRunApiV1ProjectsProjectIdRunsPostData,
  CreateRunApiV1ProjectsProjectIdRunsPostErrors,
  CreateRunApiV1ProjectsProjectIdRunsPostResponses,
  CreateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPostData,
  CreateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPostErrors,
  CreateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPostResponses,
  CreateUserApiV1SystemUsersPostData,
  CreateUserApiV1SystemUsersPostErrors,
  CreateUserApiV1SystemUsersPostResponses,
  CreateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPostData,
  CreateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPostErrors,
  CreateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPostResponses,
  CreateVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPostData,
  CreateVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPostErrors,
  CreateVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPostResponses,
  CreateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPostData,
  CreateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPostErrors,
  CreateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPostResponses,
  CurrentUserApiV1AuthMeGetData,
  CurrentUserApiV1AuthMeGetResponses,
  DeleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDeleteData,
  DeleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDeleteErrors,
  DeleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDeleteResponses,
  DeleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDeleteData,
  DeleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDeleteErrors,
  DeleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDeleteResponses,
  DeleteUserApiV1SystemUsersUserIdDeleteData,
  DeleteUserApiV1SystemUsersUserIdDeleteErrors,
  DeleteUserApiV1SystemUsersUserIdDeleteResponses,
  DisableUserApiV1SystemUsersUserIdDisablePostData,
  DisableUserApiV1SystemUsersUserIdDisablePostErrors,
  DisableUserApiV1SystemUsersUserIdDisablePostResponses,
  EnableUserApiV1SystemUsersUserIdEnablePostData,
  EnableUserApiV1SystemUsersUserIdEnablePostErrors,
  EnableUserApiV1SystemUsersUserIdEnablePostResponses,
  EventsApiV1ProjectsProjectIdRunsRunIdEventsGetData,
  EventsApiV1ProjectsProjectIdRunsRunIdEventsGetErrors,
  EventsApiV1ProjectsProjectIdRunsRunIdEventsGetResponses,
  ExportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGetData,
  ExportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGetErrors,
  ExportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGetResponses,
  GetAgentApiV1ProjectsProjectIdAgentsAgentIdGetData,
  GetAgentApiV1ProjectsProjectIdAgentsAgentIdGetErrors,
  GetAgentApiV1ProjectsProjectIdAgentsAgentIdGetResponses,
  GetDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGetData,
  GetDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGetErrors,
  GetDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGetResponses,
  GetPlanApiV1ProjectsProjectIdTestPlansPlanIdGetData,
  GetPlanApiV1ProjectsProjectIdTestPlansPlanIdGetErrors,
  GetPlanApiV1ProjectsProjectIdTestPlansPlanIdGetResponses,
  GetProjectApiV1ProjectsProjectIdGetData,
  GetProjectApiV1ProjectsProjectIdGetErrors,
  GetProjectApiV1ProjectsProjectIdGetResponses,
  GetRunApiV1ProjectsProjectIdRunsRunIdGetData,
  GetRunApiV1ProjectsProjectIdRunsRunIdGetErrors,
  GetRunApiV1ProjectsProjectIdRunsRunIdGetResponses,
  GetTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGetData,
  GetTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGetErrors,
  GetTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGetResponses,
  GetUserApiV1SystemUsersUserIdGetData,
  GetUserApiV1SystemUsersUserIdGetErrors,
  GetUserApiV1SystemUsersUserIdGetResponses,
  GetVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGetData,
  GetVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGetErrors,
  GetVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGetResponses,
  GetVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGetData,
  GetVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGetErrors,
  GetVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGetResponses,
  GetVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGetData,
  GetVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGetErrors,
  GetVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGetResponses,
  GlobalAuditApiV1SystemAuditGetData,
  GlobalAuditApiV1SystemAuditGetErrors,
  GlobalAuditApiV1SystemAuditGetResponses,
  HealthApiV1HealthGetData,
  HealthApiV1HealthGetResponses,
  ImportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPostData,
  ImportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPostErrors,
  ImportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPostResponses,
  ListAgentsApiV1ProjectsProjectIdAgentsGetData,
  ListAgentsApiV1ProjectsProjectIdAgentsGetErrors,
  ListAgentsApiV1ProjectsProjectIdAgentsGetResponses,
  ListCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGetData,
  ListCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGetErrors,
  ListCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGetResponses,
  ListCasesApiV1ProjectsProjectIdRunsRunIdCasesGetData,
  ListCasesApiV1ProjectsProjectIdRunsRunIdCasesGetErrors,
  ListCasesApiV1ProjectsProjectIdRunsRunIdCasesGetResponses,
  ListDatasetsApiV1ProjectsProjectIdDatasetsGetData,
  ListDatasetsApiV1ProjectsProjectIdDatasetsGetErrors,
  ListDatasetsApiV1ProjectsProjectIdDatasetsGetResponses,
  ListMembersApiV1ProjectsProjectIdMembersGetData,
  ListMembersApiV1ProjectsProjectIdMembersGetErrors,
  ListMembersApiV1ProjectsProjectIdMembersGetResponses,
  ListPlansApiV1ProjectsProjectIdTestPlansGetData,
  ListPlansApiV1ProjectsProjectIdTestPlansGetErrors,
  ListPlansApiV1ProjectsProjectIdTestPlansGetResponses,
  ListProjectsApiV1ProjectsGetData,
  ListProjectsApiV1ProjectsGetResponses,
  ListRunsApiV1ProjectsProjectIdRunsGetData,
  ListRunsApiV1ProjectsProjectIdRunsGetErrors,
  ListRunsApiV1ProjectsProjectIdRunsGetResponses,
  ListTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGetData,
  ListTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGetErrors,
  ListTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGetResponses,
  ListUsersApiV1SystemUsersGetData,
  ListUsersApiV1SystemUsersGetErrors,
  ListUsersApiV1SystemUsersGetResponses,
  ListVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGetData,
  ListVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGetErrors,
  ListVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGetResponses,
  ListVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGetData,
  ListVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGetErrors,
  ListVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGetResponses,
  ListVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGetData,
  ListVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGetErrors,
  ListVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGetResponses,
  LoginApiV1AuthLoginPostData,
  LoginApiV1AuthLoginPostErrors,
  LoginApiV1AuthLoginPostResponses,
  LogoutApiV1AuthLogoutPostData,
  LogoutApiV1AuthLogoutPostErrors,
  LogoutApiV1AuthLogoutPostResponses,
  ProjectAuditApiV1ProjectsProjectIdAuditGetData,
  ProjectAuditApiV1ProjectsProjectIdAuditGetErrors,
  ProjectAuditApiV1ProjectsProjectIdAuditGetResponses,
  PublishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPostData,
  PublishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPostErrors,
  PublishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPostResponses,
  PublishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPostData,
  PublishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPostErrors,
  PublishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPostResponses,
  PublishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPostData,
  PublishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPostErrors,
  PublishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPostResponses,
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteData,
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors,
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses,
  RenameProjectApiV1ProjectsProjectIdPatchData,
  RenameProjectApiV1ProjectsProjectIdPatchErrors,
  RenameProjectApiV1ProjectsProjectIdPatchResponses,
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostData,
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors,
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses,
  UpdateAgentApiV1ProjectsProjectIdAgentsAgentIdPatchData,
  UpdateAgentApiV1ProjectsProjectIdAgentsAgentIdPatchErrors,
  UpdateAgentApiV1ProjectsProjectIdAgentsAgentIdPatchResponses,
  UpdateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatchData,
  UpdateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatchErrors,
  UpdateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatchResponses,
  UpdateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatchData,
  UpdateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatchErrors,
  UpdateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatchResponses,
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchData,
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors,
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses,
  UpdatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatchData,
  UpdatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatchErrors,
  UpdatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatchResponses,
  UpdateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatchData,
  UpdateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatchErrors,
  UpdateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatchResponses,
  UpdateUserApiV1SystemUsersUserIdPatchData,
  UpdateUserApiV1SystemUsersUserIdPatchErrors,
  UpdateUserApiV1SystemUsersUserIdPatchResponses,
  UpdateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatchData,
  UpdateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatchErrors,
  UpdateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatchResponses,
  UpdateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatchData,
  UpdateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatchErrors,
  UpdateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatchResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>,
): RequestResult<
  LoginApiV1AuthLoginPostResponses,
  LoginApiV1AuthLoginPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    LoginApiV1AuthLoginPostResponses,
    LoginApiV1AuthLoginPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Logout
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>,
): RequestResult<
  LogoutApiV1AuthLogoutPostResponses,
  LogoutApiV1AuthLogoutPostErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    LogoutApiV1AuthLogoutPostResponses,
    LogoutApiV1AuthLogoutPostErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/logout", ...options });

/**
 * Current User
 */
export const currentUserApiV1AuthMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<CurrentUserApiV1AuthMeGetData, ThrowOnError>,
): RequestResult<CurrentUserApiV1AuthMeGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    CurrentUserApiV1AuthMeGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/auth/me", ...options });

/**
 * Health
 */
export const healthApiV1HealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthApiV1HealthGetData, ThrowOnError>,
): RequestResult<HealthApiV1HealthGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthApiV1HealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/health", ...options });

/**
 * List Projects
 */
export const listProjectsApiV1ProjectsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListProjectsApiV1ProjectsGetData, ThrowOnError>,
): RequestResult<
  ListProjectsApiV1ProjectsGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListProjectsApiV1ProjectsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/projects", ...options });

/**
 * Create Project
 */
export const createProjectApiV1ProjectsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateProjectApiV1ProjectsPostData, ThrowOnError>,
): RequestResult<
  CreateProjectApiV1ProjectsPostResponses,
  CreateProjectApiV1ProjectsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectApiV1ProjectsPostResponses,
    CreateProjectApiV1ProjectsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Project
 */
export const getProjectApiV1ProjectsProjectIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetProjectApiV1ProjectsProjectIdGetData, ThrowOnError>,
): RequestResult<
  GetProjectApiV1ProjectsProjectIdGetResponses,
  GetProjectApiV1ProjectsProjectIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetProjectApiV1ProjectsProjectIdGetResponses,
    GetProjectApiV1ProjectsProjectIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}", ...options });

/**
 * Rename Project
 */
export const renameProjectApiV1ProjectsProjectIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RenameProjectApiV1ProjectsProjectIdPatchData, ThrowOnError>,
): RequestResult<
  RenameProjectApiV1ProjectsProjectIdPatchResponses,
  RenameProjectApiV1ProjectsProjectIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    RenameProjectApiV1ProjectsProjectIdPatchResponses,
    RenameProjectApiV1ProjectsProjectIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Agents
 */
export const listAgentsApiV1ProjectsProjectIdAgentsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListAgentsApiV1ProjectsProjectIdAgentsGetData, ThrowOnError>,
): RequestResult<
  ListAgentsApiV1ProjectsProjectIdAgentsGetResponses,
  ListAgentsApiV1ProjectsProjectIdAgentsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListAgentsApiV1ProjectsProjectIdAgentsGetResponses,
    ListAgentsApiV1ProjectsProjectIdAgentsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/agents", ...options });

/**
 * Create Agent
 */
export const createAgentApiV1ProjectsProjectIdAgentsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateAgentApiV1ProjectsProjectIdAgentsPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateAgentApiV1ProjectsProjectIdAgentsPostResponses,
  CreateAgentApiV1ProjectsProjectIdAgentsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateAgentApiV1ProjectsProjectIdAgentsPostResponses,
    CreateAgentApiV1ProjectsProjectIdAgentsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/agents",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Agent
 */
export const getAgentApiV1ProjectsProjectIdAgentsAgentIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetAgentApiV1ProjectsProjectIdAgentsAgentIdGetData,
    ThrowOnError
  >,
): RequestResult<
  GetAgentApiV1ProjectsProjectIdAgentsAgentIdGetResponses,
  GetAgentApiV1ProjectsProjectIdAgentsAgentIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAgentApiV1ProjectsProjectIdAgentsAgentIdGetResponses,
    GetAgentApiV1ProjectsProjectIdAgentsAgentIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/agents/{agent_id}", ...options });

/**
 * Update Agent
 */
export const updateAgentApiV1ProjectsProjectIdAgentsAgentIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateAgentApiV1ProjectsProjectIdAgentsAgentIdPatchData,
    ThrowOnError
  >,
): RequestResult<
  UpdateAgentApiV1ProjectsProjectIdAgentsAgentIdPatchResponses,
  UpdateAgentApiV1ProjectsProjectIdAgentsAgentIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateAgentApiV1ProjectsProjectIdAgentsAgentIdPatchResponses,
    UpdateAgentApiV1ProjectsProjectIdAgentsAgentIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/agents/{agent_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Versions
 */
export const listVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGetData,
    ThrowOnError
  >,
): RequestResult<
  ListVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGetResponses,
  ListVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGetResponses,
    ListVersionsApiV1ProjectsProjectIdAgentsAgentIdVersionsGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/agents/{agent_id}/versions",
    ...options,
  });

/**
 * Create Version
 */
export const createVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPostResponses,
  CreateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPostResponses,
    CreateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/agents/{agent_id}/versions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Version
 */
export const getVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGetData,
      ThrowOnError
    >,
  ): RequestResult<
    GetVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGetResponses,
    GetVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      GetVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGetResponses,
      GetVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/agents/{agent_id}/versions/{version_id}",
      ...options,
    });

/**
 * Update Version
 */
export const updateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatchData,
      ThrowOnError
    >,
  ): RequestResult<
    UpdateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatchResponses,
    UpdateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatchErrors,
    ThrowOnError
  > =>
    (options.client ?? client).patch<
      UpdateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatchResponses,
      UpdateVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPatchErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/agents/{agent_id}/versions/{version_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * Publish Version
 */
export const publishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      PublishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPostData,
      ThrowOnError
    >,
  ): RequestResult<
    PublishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPostResponses,
    PublishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPostErrors,
    ThrowOnError
  > =>
    (options.client ?? client).post<
      PublishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPostResponses,
      PublishVersionApiV1ProjectsProjectIdAgentsAgentIdVersionsVersionIdPublishPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/agents/{agent_id}/versions/{version_id}/publish",
      ...options,
    });

/**
 * Archive Project
 */
export const archiveProjectApiV1ProjectsProjectIdArchivePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ArchiveProjectApiV1ProjectsProjectIdArchivePostData,
    ThrowOnError
  >,
): RequestResult<
  ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses,
  ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses,
    ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/archive", ...options });

/**
 * Project Audit
 */
export const projectAuditApiV1ProjectsProjectIdAuditGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ProjectAuditApiV1ProjectsProjectIdAuditGetData,
    ThrowOnError
  >,
): RequestResult<
  ProjectAuditApiV1ProjectsProjectIdAuditGetResponses,
  ProjectAuditApiV1ProjectsProjectIdAuditGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectAuditApiV1ProjectsProjectIdAuditGetResponses,
    ProjectAuditApiV1ProjectsProjectIdAuditGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/audit", ...options });

/**
 * List Datasets
 */
export const listDatasetsApiV1ProjectsProjectIdDatasetsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListDatasetsApiV1ProjectsProjectIdDatasetsGetData,
    ThrowOnError
  >,
): RequestResult<
  ListDatasetsApiV1ProjectsProjectIdDatasetsGetResponses,
  ListDatasetsApiV1ProjectsProjectIdDatasetsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListDatasetsApiV1ProjectsProjectIdDatasetsGetResponses,
    ListDatasetsApiV1ProjectsProjectIdDatasetsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/datasets", ...options });

/**
 * Create Dataset
 */
export const createDatasetApiV1ProjectsProjectIdDatasetsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateDatasetApiV1ProjectsProjectIdDatasetsPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateDatasetApiV1ProjectsProjectIdDatasetsPostResponses,
  CreateDatasetApiV1ProjectsProjectIdDatasetsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateDatasetApiV1ProjectsProjectIdDatasetsPostResponses,
    CreateDatasetApiV1ProjectsProjectIdDatasetsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/datasets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Dataset
 */
export const getDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGetData,
    ThrowOnError
  >,
): RequestResult<
  GetDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGetResponses,
  GetDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGetResponses,
    GetDatasetApiV1ProjectsProjectIdDatasetsDatasetIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/datasets/{dataset_id}", ...options });

/**
 * Update Dataset
 */
export const updateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatchData,
    ThrowOnError
  >,
): RequestResult<
  UpdateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatchResponses,
  UpdateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatchResponses,
    UpdateDatasetApiV1ProjectsProjectIdDatasetsDatasetIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/datasets/{dataset_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Versions
 */
export const listVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGetData,
    ThrowOnError
  >,
): RequestResult<
  ListVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGetResponses,
  ListVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGetResponses,
    ListVersionsApiV1ProjectsProjectIdDatasetsDatasetIdVersionsGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions",
    ...options,
  });

/**
 * Create Version
 */
export const createVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CreateVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPostData,
      ThrowOnError
    >,
  ): RequestResult<
    CreateVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPostResponses,
    CreateVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPostErrors,
    ThrowOnError
  > =>
    (options.client ?? client).post<
      CreateVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPostResponses,
      CreateVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions",
      ...options,
    });

/**
 * Get Version
 */
export const getVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGetData,
      ThrowOnError
    >,
  ): RequestResult<
    GetVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGetResponses,
    GetVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      GetVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGetResponses,
      GetVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions/{version_id}",
      ...options,
    });

/**
 * List Cases
 */
export const listCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      ListCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGetData,
      ThrowOnError
    >,
  ): RequestResult<
    ListCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGetResponses,
    ListCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      ListCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGetResponses,
      ListCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions/{version_id}/cases",
      ...options,
    });

/**
 * Add Case
 */
export const addCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      AddCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPostData,
      ThrowOnError
    >,
  ): RequestResult<
    AddCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPostResponses,
    AddCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPostErrors,
    ThrowOnError
  > =>
    (options.client ?? client).post<
      AddCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPostResponses,
      AddCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions/{version_id}/cases",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * Delete Case
 */
export const deleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDeleteData,
      ThrowOnError
    >,
  ): RequestResult<
    DeleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDeleteResponses,
    DeleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDeleteErrors,
    ThrowOnError
  > =>
    (options.client ?? client).delete<
      DeleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDeleteResponses,
      DeleteCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdDeleteErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions/{version_id}/cases/{case_id}",
      ...options,
    });

/**
 * Update Case
 */
export const updateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatchData,
      ThrowOnError
    >,
  ): RequestResult<
    UpdateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatchResponses,
    UpdateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatchErrors,
    ThrowOnError
  > =>
    (options.client ?? client).patch<
      UpdateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatchResponses,
      UpdateCaseApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdCasesCaseIdPatchErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions/{version_id}/cases/{case_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * Export Cases
 */
export const exportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      ExportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGetData,
      ThrowOnError
    >,
  ): RequestResult<
    ExportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGetResponses,
    ExportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      ExportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGetResponses,
      ExportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdExportGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions/{version_id}/export",
      ...options,
    });

/**
 * Import Cases
 */
export const importCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      ImportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPostData,
      ThrowOnError
    >,
  ): RequestResult<
    ImportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPostResponses,
    ImportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPostErrors,
    ThrowOnError
  > =>
    (options.client ?? client).post<
      ImportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPostResponses,
      ImportCasesApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdImportPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions/{version_id}/import",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * Publish Version
 */
export const publishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      PublishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPostData,
      ThrowOnError
    >,
  ): RequestResult<
    PublishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPostResponses,
    PublishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPostErrors,
    ThrowOnError
  > =>
    (options.client ?? client).post<
      PublishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPostResponses,
      PublishVersionApiV1ProjectsProjectIdDatasetsDatasetIdVersionsVersionIdPublishPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/datasets/{dataset_id}/versions/{version_id}/publish",
      ...options,
    });

/**
 * List Templates
 */
export const listTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGetData,
    ThrowOnError
  >,
): RequestResult<
  ListTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGetResponses,
  ListTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGetResponses,
    ListTemplatesApiV1ProjectsProjectIdEnvironmentTemplatesGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/environment-templates", ...options });

/**
 * Create Template
 */
export const createTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPostResponses,
  CreateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPostResponses,
    CreateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/environment-templates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Template
 */
export const deleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDeleteData,
      ThrowOnError
    >,
  ): RequestResult<
    DeleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDeleteResponses,
    DeleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDeleteErrors,
    ThrowOnError
  > =>
    (options.client ?? client).delete<
      DeleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDeleteResponses,
      DeleteTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdDeleteErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/environment-templates/{template_id}",
      ...options,
    });

/**
 * Get Template
 */
export const getTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGetData,
      ThrowOnError
    >,
  ): RequestResult<
    GetTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGetResponses,
    GetTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      GetTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGetResponses,
      GetTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/environment-templates/{template_id}",
      ...options,
    });

/**
 * Update Template
 */
export const updateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatchData,
      ThrowOnError
    >,
  ): RequestResult<
    UpdateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatchResponses,
    UpdateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatchErrors,
    ThrowOnError
  > =>
    (options.client ?? client).patch<
      UpdateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatchResponses,
      UpdateTemplateApiV1ProjectsProjectIdEnvironmentTemplatesTemplateIdPatchErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/environment-templates/{template_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * List Members
 */
export const listMembersApiV1ProjectsProjectIdMembersGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListMembersApiV1ProjectsProjectIdMembersGetData,
    ThrowOnError
  >,
): RequestResult<
  ListMembersApiV1ProjectsProjectIdMembersGetResponses,
  ListMembersApiV1ProjectsProjectIdMembersGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListMembersApiV1ProjectsProjectIdMembersGetResponses,
    ListMembersApiV1ProjectsProjectIdMembersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/members", ...options });

/**
 * Add Member
 */
export const addMemberApiV1ProjectsProjectIdMembersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AddMemberApiV1ProjectsProjectIdMembersPostData,
    ThrowOnError
  >,
): RequestResult<
  AddMemberApiV1ProjectsProjectIdMembersPostResponses,
  AddMemberApiV1ProjectsProjectIdMembersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AddMemberApiV1ProjectsProjectIdMembersPostResponses,
    AddMemberApiV1ProjectsProjectIdMembersPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/members",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Member
 */
export const removeMemberApiV1ProjectsProjectIdMembersUserIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses,
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses,
    RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/members/{user_id}", ...options });

/**
 * Update Member
 */
export const updateMemberApiV1ProjectsProjectIdMembersUserIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchData,
    ThrowOnError
  >,
): RequestResult<
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses,
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses,
    UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/members/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Runs
 */
export const listRunsApiV1ProjectsProjectIdRunsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListRunsApiV1ProjectsProjectIdRunsGetData, ThrowOnError>,
): RequestResult<
  ListRunsApiV1ProjectsProjectIdRunsGetResponses,
  ListRunsApiV1ProjectsProjectIdRunsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListRunsApiV1ProjectsProjectIdRunsGetResponses,
    ListRunsApiV1ProjectsProjectIdRunsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/runs", ...options });

/**
 * Create Run
 */
export const createRunApiV1ProjectsProjectIdRunsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRunApiV1ProjectsProjectIdRunsPostData, ThrowOnError>,
): RequestResult<
  CreateRunApiV1ProjectsProjectIdRunsPostResponses,
  CreateRunApiV1ProjectsProjectIdRunsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateRunApiV1ProjectsProjectIdRunsPostResponses,
    CreateRunApiV1ProjectsProjectIdRunsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/runs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Run
 */
export const getRunApiV1ProjectsProjectIdRunsRunIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetRunApiV1ProjectsProjectIdRunsRunIdGetData, ThrowOnError>,
): RequestResult<
  GetRunApiV1ProjectsProjectIdRunsRunIdGetResponses,
  GetRunApiV1ProjectsProjectIdRunsRunIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetRunApiV1ProjectsProjectIdRunsRunIdGetResponses,
    GetRunApiV1ProjectsProjectIdRunsRunIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/runs/{run_id}", ...options });

/**
 * Cancel Run
 */
export const cancelRunApiV1ProjectsProjectIdRunsRunIdCancelPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CancelRunApiV1ProjectsProjectIdRunsRunIdCancelPostData,
    ThrowOnError
  >,
): RequestResult<
  CancelRunApiV1ProjectsProjectIdRunsRunIdCancelPostResponses,
  CancelRunApiV1ProjectsProjectIdRunsRunIdCancelPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CancelRunApiV1ProjectsProjectIdRunsRunIdCancelPostResponses,
    CancelRunApiV1ProjectsProjectIdRunsRunIdCancelPostErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/runs/{run_id}/cancel", ...options });

/**
 * List Cases
 */
export const listCasesApiV1ProjectsProjectIdRunsRunIdCasesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListCasesApiV1ProjectsProjectIdRunsRunIdCasesGetData,
    ThrowOnError
  >,
): RequestResult<
  ListCasesApiV1ProjectsProjectIdRunsRunIdCasesGetResponses,
  ListCasesApiV1ProjectsProjectIdRunsRunIdCasesGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListCasesApiV1ProjectsProjectIdRunsRunIdCasesGetResponses,
    ListCasesApiV1ProjectsProjectIdRunsRunIdCasesGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/runs/{run_id}/cases", ...options });

/**
 * Events
 */
export const eventsApiV1ProjectsProjectIdRunsRunIdEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    EventsApiV1ProjectsProjectIdRunsRunIdEventsGetData,
    ThrowOnError
  >,
): RequestResult<
  EventsApiV1ProjectsProjectIdRunsRunIdEventsGetResponses,
  EventsApiV1ProjectsProjectIdRunsRunIdEventsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    EventsApiV1ProjectsProjectIdRunsRunIdEventsGetResponses,
    EventsApiV1ProjectsProjectIdRunsRunIdEventsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/runs/{run_id}/events", ...options });

/**
 * Apply Result
 */
export const applyResultApiV1ProjectsProjectIdRunsRunIdResultPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApplyResultApiV1ProjectsProjectIdRunsRunIdResultPostData,
    ThrowOnError
  >,
): RequestResult<
  ApplyResultApiV1ProjectsProjectIdRunsRunIdResultPostResponses,
  ApplyResultApiV1ProjectsProjectIdRunsRunIdResultPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ApplyResultApiV1ProjectsProjectIdRunsRunIdResultPostResponses,
    ApplyResultApiV1ProjectsProjectIdRunsRunIdResultPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/runs/{run_id}/result",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Plans
 */
export const listPlansApiV1ProjectsProjectIdTestPlansGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListPlansApiV1ProjectsProjectIdTestPlansGetData,
    ThrowOnError
  >,
): RequestResult<
  ListPlansApiV1ProjectsProjectIdTestPlansGetResponses,
  ListPlansApiV1ProjectsProjectIdTestPlansGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListPlansApiV1ProjectsProjectIdTestPlansGetResponses,
    ListPlansApiV1ProjectsProjectIdTestPlansGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/test-plans", ...options });

/**
 * Create Plan
 */
export const createPlanApiV1ProjectsProjectIdTestPlansPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreatePlanApiV1ProjectsProjectIdTestPlansPostData,
    ThrowOnError
  >,
): RequestResult<
  CreatePlanApiV1ProjectsProjectIdTestPlansPostResponses,
  CreatePlanApiV1ProjectsProjectIdTestPlansPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreatePlanApiV1ProjectsProjectIdTestPlansPostResponses,
    CreatePlanApiV1ProjectsProjectIdTestPlansPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/test-plans",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Plan
 */
export const getPlanApiV1ProjectsProjectIdTestPlansPlanIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPlanApiV1ProjectsProjectIdTestPlansPlanIdGetData,
    ThrowOnError
  >,
): RequestResult<
  GetPlanApiV1ProjectsProjectIdTestPlansPlanIdGetResponses,
  GetPlanApiV1ProjectsProjectIdTestPlansPlanIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPlanApiV1ProjectsProjectIdTestPlansPlanIdGetResponses,
    GetPlanApiV1ProjectsProjectIdTestPlansPlanIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/test-plans/{plan_id}", ...options });

/**
 * Update Plan
 */
export const updatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatchData,
    ThrowOnError
  >,
): RequestResult<
  UpdatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatchResponses,
  UpdatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatchResponses,
    UpdatePlanApiV1ProjectsProjectIdTestPlansPlanIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/test-plans/{plan_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Versions
 */
export const listVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGetData,
    ThrowOnError
  >,
): RequestResult<
  ListVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGetResponses,
  ListVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGetResponses,
    ListVersionsApiV1ProjectsProjectIdTestPlansPlanIdVersionsGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/test-plans/{plan_id}/versions",
    ...options,
  });

/**
 * Create Version
 */
export const createVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPostResponses,
  CreateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPostResponses,
    CreateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/test-plans/{plan_id}/versions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Version
 */
export const getVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGetData,
      ThrowOnError
    >,
  ): RequestResult<
    GetVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGetResponses,
    GetVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      GetVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGetResponses,
      GetVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/test-plans/{plan_id}/versions/{version_id}",
      ...options,
    });

/**
 * Update Version
 */
export const updateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatchData,
      ThrowOnError
    >,
  ): RequestResult<
    UpdateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatchResponses,
    UpdateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatchErrors,
    ThrowOnError
  > =>
    (options.client ?? client).patch<
      UpdateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatchResponses,
      UpdateVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPatchErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/test-plans/{plan_id}/versions/{version_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * Publish Version
 */
export const publishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      PublishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPostData,
      ThrowOnError
    >,
  ): RequestResult<
    PublishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPostResponses,
    PublishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPostErrors,
    ThrowOnError
  > =>
    (options.client ?? client).post<
      PublishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPostResponses,
      PublishVersionApiV1ProjectsProjectIdTestPlansPlanIdVersionsVersionIdPublishPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/projects/{project_id}/test-plans/{plan_id}/versions/{version_id}/publish",
      ...options,
    });

/**
 * Global Audit
 */
export const globalAuditApiV1SystemAuditGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GlobalAuditApiV1SystemAuditGetData, ThrowOnError>,
): RequestResult<
  GlobalAuditApiV1SystemAuditGetResponses,
  GlobalAuditApiV1SystemAuditGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GlobalAuditApiV1SystemAuditGetResponses,
    GlobalAuditApiV1SystemAuditGetErrors,
    ThrowOnError
  >({ url: "/api/v1/system/audit", ...options });

/**
 * List Users
 */
export const listUsersApiV1SystemUsersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUsersApiV1SystemUsersGetData, ThrowOnError>,
): RequestResult<
  ListUsersApiV1SystemUsersGetResponses,
  ListUsersApiV1SystemUsersGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListUsersApiV1SystemUsersGetResponses,
    ListUsersApiV1SystemUsersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users", ...options });

/**
 * Create User
 */
export const createUserApiV1SystemUsersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUserApiV1SystemUsersPostData, ThrowOnError>,
): RequestResult<
  CreateUserApiV1SystemUsersPostResponses,
  CreateUserApiV1SystemUsersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateUserApiV1SystemUsersPostResponses,
    CreateUserApiV1SystemUsersPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/system/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete User
 */
export const deleteUserApiV1SystemUsersUserIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteUserApiV1SystemUsersUserIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteUserApiV1SystemUsersUserIdDeleteResponses,
  DeleteUserApiV1SystemUsersUserIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteUserApiV1SystemUsersUserIdDeleteResponses,
    DeleteUserApiV1SystemUsersUserIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users/{user_id}", ...options });

/**
 * Get User
 */
export const getUserApiV1SystemUsersUserIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserApiV1SystemUsersUserIdGetData, ThrowOnError>,
): RequestResult<
  GetUserApiV1SystemUsersUserIdGetResponses,
  GetUserApiV1SystemUsersUserIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserApiV1SystemUsersUserIdGetResponses,
    GetUserApiV1SystemUsersUserIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users/{user_id}", ...options });

/**
 * Update User
 */
export const updateUserApiV1SystemUsersUserIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUserApiV1SystemUsersUserIdPatchData, ThrowOnError>,
): RequestResult<
  UpdateUserApiV1SystemUsersUserIdPatchResponses,
  UpdateUserApiV1SystemUsersUserIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateUserApiV1SystemUsersUserIdPatchResponses,
    UpdateUserApiV1SystemUsersUserIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/system/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Disable User
 */
export const disableUserApiV1SystemUsersUserIdDisablePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DisableUserApiV1SystemUsersUserIdDisablePostData,
    ThrowOnError
  >,
): RequestResult<
  DisableUserApiV1SystemUsersUserIdDisablePostResponses,
  DisableUserApiV1SystemUsersUserIdDisablePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DisableUserApiV1SystemUsersUserIdDisablePostResponses,
    DisableUserApiV1SystemUsersUserIdDisablePostErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users/{user_id}/disable", ...options });

/**
 * Enable User
 */
export const enableUserApiV1SystemUsersUserIdEnablePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    EnableUserApiV1SystemUsersUserIdEnablePostData,
    ThrowOnError
  >,
): RequestResult<
  EnableUserApiV1SystemUsersUserIdEnablePostResponses,
  EnableUserApiV1SystemUsersUserIdEnablePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    EnableUserApiV1SystemUsersUserIdEnablePostResponses,
    EnableUserApiV1SystemUsersUserIdEnablePostErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users/{user_id}/enable", ...options });

/**
 * Reset Password
 */
export const resetPasswordApiV1SystemUsersUserIdResetPasswordPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ResetPasswordApiV1SystemUsersUserIdResetPasswordPostData,
    ThrowOnError
  >,
): RequestResult<
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses,
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses,
    ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/system/users/{user_id}/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
