// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AddMemberApiV1ProjectsProjectIdMembersPostData,
  AddMemberApiV1ProjectsProjectIdMembersPostErrors,
  AddMemberApiV1ProjectsProjectIdMembersPostResponses,
  ArchiveProjectApiV1ProjectsProjectIdArchivePostData,
  ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors,
  ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses,
  CreateProjectApiV1ProjectsPostData,
  CreateProjectApiV1ProjectsPostErrors,
  CreateProjectApiV1ProjectsPostResponses,
  CreateUserApiV1SystemUsersPostData,
  CreateUserApiV1SystemUsersPostErrors,
  CreateUserApiV1SystemUsersPostResponses,
  CurrentUserApiV1AuthMeGetData,
  CurrentUserApiV1AuthMeGetResponses,
  DeleteUserApiV1SystemUsersUserIdDeleteData,
  DeleteUserApiV1SystemUsersUserIdDeleteErrors,
  DeleteUserApiV1SystemUsersUserIdDeleteResponses,
  DisableUserApiV1SystemUsersUserIdDisablePostData,
  DisableUserApiV1SystemUsersUserIdDisablePostErrors,
  DisableUserApiV1SystemUsersUserIdDisablePostResponses,
  EnableUserApiV1SystemUsersUserIdEnablePostData,
  EnableUserApiV1SystemUsersUserIdEnablePostErrors,
  EnableUserApiV1SystemUsersUserIdEnablePostResponses,
  GetProjectApiV1ProjectsProjectIdGetData,
  GetProjectApiV1ProjectsProjectIdGetErrors,
  GetProjectApiV1ProjectsProjectIdGetResponses,
  GetUserApiV1SystemUsersUserIdGetData,
  GetUserApiV1SystemUsersUserIdGetErrors,
  GetUserApiV1SystemUsersUserIdGetResponses,
  GlobalAuditApiV1SystemAuditGetData,
  GlobalAuditApiV1SystemAuditGetErrors,
  GlobalAuditApiV1SystemAuditGetResponses,
  HealthApiV1HealthGetData,
  HealthApiV1HealthGetResponses,
  ListMembersApiV1ProjectsProjectIdMembersGetData,
  ListMembersApiV1ProjectsProjectIdMembersGetErrors,
  ListMembersApiV1ProjectsProjectIdMembersGetResponses,
  ListProjectsApiV1ProjectsGetData,
  ListProjectsApiV1ProjectsGetResponses,
  ListUsersApiV1SystemUsersGetData,
  ListUsersApiV1SystemUsersGetErrors,
  ListUsersApiV1SystemUsersGetResponses,
  LoginApiV1AuthLoginPostData,
  LoginApiV1AuthLoginPostErrors,
  LoginApiV1AuthLoginPostResponses,
  LogoutApiV1AuthLogoutPostData,
  LogoutApiV1AuthLogoutPostErrors,
  LogoutApiV1AuthLogoutPostResponses,
  ProjectAuditApiV1ProjectsProjectIdAuditGetData,
  ProjectAuditApiV1ProjectsProjectIdAuditGetErrors,
  ProjectAuditApiV1ProjectsProjectIdAuditGetResponses,
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteData,
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors,
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses,
  RenameProjectApiV1ProjectsProjectIdPatchData,
  RenameProjectApiV1ProjectsProjectIdPatchErrors,
  RenameProjectApiV1ProjectsProjectIdPatchResponses,
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostData,
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors,
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses,
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchData,
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors,
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses,
  UpdateUserApiV1SystemUsersUserIdPatchData,
  UpdateUserApiV1SystemUsersUserIdPatchErrors,
  UpdateUserApiV1SystemUsersUserIdPatchResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>,
): RequestResult<
  LoginApiV1AuthLoginPostResponses,
  LoginApiV1AuthLoginPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    LoginApiV1AuthLoginPostResponses,
    LoginApiV1AuthLoginPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Logout
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>,
): RequestResult<
  LogoutApiV1AuthLogoutPostResponses,
  LogoutApiV1AuthLogoutPostErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    LogoutApiV1AuthLogoutPostResponses,
    LogoutApiV1AuthLogoutPostErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/logout", ...options });

/**
 * Current User
 */
export const currentUserApiV1AuthMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<CurrentUserApiV1AuthMeGetData, ThrowOnError>,
): RequestResult<CurrentUserApiV1AuthMeGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    CurrentUserApiV1AuthMeGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/auth/me", ...options });

/**
 * Health
 */
export const healthApiV1HealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthApiV1HealthGetData, ThrowOnError>,
): RequestResult<HealthApiV1HealthGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthApiV1HealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/health", ...options });

/**
 * List Projects
 */
export const listProjectsApiV1ProjectsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListProjectsApiV1ProjectsGetData, ThrowOnError>,
): RequestResult<
  ListProjectsApiV1ProjectsGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListProjectsApiV1ProjectsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/projects", ...options });

/**
 * Create Project
 */
export const createProjectApiV1ProjectsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateProjectApiV1ProjectsPostData, ThrowOnError>,
): RequestResult<
  CreateProjectApiV1ProjectsPostResponses,
  CreateProjectApiV1ProjectsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectApiV1ProjectsPostResponses,
    CreateProjectApiV1ProjectsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Project
 */
export const getProjectApiV1ProjectsProjectIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetProjectApiV1ProjectsProjectIdGetData, ThrowOnError>,
): RequestResult<
  GetProjectApiV1ProjectsProjectIdGetResponses,
  GetProjectApiV1ProjectsProjectIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetProjectApiV1ProjectsProjectIdGetResponses,
    GetProjectApiV1ProjectsProjectIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}", ...options });

/**
 * Rename Project
 */
export const renameProjectApiV1ProjectsProjectIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RenameProjectApiV1ProjectsProjectIdPatchData, ThrowOnError>,
): RequestResult<
  RenameProjectApiV1ProjectsProjectIdPatchResponses,
  RenameProjectApiV1ProjectsProjectIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    RenameProjectApiV1ProjectsProjectIdPatchResponses,
    RenameProjectApiV1ProjectsProjectIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Archive Project
 */
export const archiveProjectApiV1ProjectsProjectIdArchivePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ArchiveProjectApiV1ProjectsProjectIdArchivePostData,
    ThrowOnError
  >,
): RequestResult<
  ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses,
  ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses,
    ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/archive", ...options });

/**
 * Project Audit
 */
export const projectAuditApiV1ProjectsProjectIdAuditGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ProjectAuditApiV1ProjectsProjectIdAuditGetData,
    ThrowOnError
  >,
): RequestResult<
  ProjectAuditApiV1ProjectsProjectIdAuditGetResponses,
  ProjectAuditApiV1ProjectsProjectIdAuditGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ProjectAuditApiV1ProjectsProjectIdAuditGetResponses,
    ProjectAuditApiV1ProjectsProjectIdAuditGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/audit", ...options });

/**
 * List Members
 */
export const listMembersApiV1ProjectsProjectIdMembersGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListMembersApiV1ProjectsProjectIdMembersGetData,
    ThrowOnError
  >,
): RequestResult<
  ListMembersApiV1ProjectsProjectIdMembersGetResponses,
  ListMembersApiV1ProjectsProjectIdMembersGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListMembersApiV1ProjectsProjectIdMembersGetResponses,
    ListMembersApiV1ProjectsProjectIdMembersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/members", ...options });

/**
 * Add Member
 */
export const addMemberApiV1ProjectsProjectIdMembersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AddMemberApiV1ProjectsProjectIdMembersPostData,
    ThrowOnError
  >,
): RequestResult<
  AddMemberApiV1ProjectsProjectIdMembersPostResponses,
  AddMemberApiV1ProjectsProjectIdMembersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AddMemberApiV1ProjectsProjectIdMembersPostResponses,
    AddMemberApiV1ProjectsProjectIdMembersPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/members",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Member
 */
export const removeMemberApiV1ProjectsProjectIdMembersUserIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses,
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses,
    RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/members/{user_id}", ...options });

/**
 * Update Member
 */
export const updateMemberApiV1ProjectsProjectIdMembersUserIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchData,
    ThrowOnError
  >,
): RequestResult<
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses,
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses,
    UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/members/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Global Audit
 */
export const globalAuditApiV1SystemAuditGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GlobalAuditApiV1SystemAuditGetData, ThrowOnError>,
): RequestResult<
  GlobalAuditApiV1SystemAuditGetResponses,
  GlobalAuditApiV1SystemAuditGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GlobalAuditApiV1SystemAuditGetResponses,
    GlobalAuditApiV1SystemAuditGetErrors,
    ThrowOnError
  >({ url: "/api/v1/system/audit", ...options });

/**
 * List Users
 */
export const listUsersApiV1SystemUsersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUsersApiV1SystemUsersGetData, ThrowOnError>,
): RequestResult<
  ListUsersApiV1SystemUsersGetResponses,
  ListUsersApiV1SystemUsersGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListUsersApiV1SystemUsersGetResponses,
    ListUsersApiV1SystemUsersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users", ...options });

/**
 * Create User
 */
export const createUserApiV1SystemUsersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUserApiV1SystemUsersPostData, ThrowOnError>,
): RequestResult<
  CreateUserApiV1SystemUsersPostResponses,
  CreateUserApiV1SystemUsersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateUserApiV1SystemUsersPostResponses,
    CreateUserApiV1SystemUsersPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/system/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete User
 */
export const deleteUserApiV1SystemUsersUserIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteUserApiV1SystemUsersUserIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteUserApiV1SystemUsersUserIdDeleteResponses,
  DeleteUserApiV1SystemUsersUserIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteUserApiV1SystemUsersUserIdDeleteResponses,
    DeleteUserApiV1SystemUsersUserIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users/{user_id}", ...options });

/**
 * Get User
 */
export const getUserApiV1SystemUsersUserIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserApiV1SystemUsersUserIdGetData, ThrowOnError>,
): RequestResult<
  GetUserApiV1SystemUsersUserIdGetResponses,
  GetUserApiV1SystemUsersUserIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserApiV1SystemUsersUserIdGetResponses,
    GetUserApiV1SystemUsersUserIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users/{user_id}", ...options });

/**
 * Update User
 */
export const updateUserApiV1SystemUsersUserIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUserApiV1SystemUsersUserIdPatchData, ThrowOnError>,
): RequestResult<
  UpdateUserApiV1SystemUsersUserIdPatchResponses,
  UpdateUserApiV1SystemUsersUserIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateUserApiV1SystemUsersUserIdPatchResponses,
    UpdateUserApiV1SystemUsersUserIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/system/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Disable User
 */
export const disableUserApiV1SystemUsersUserIdDisablePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DisableUserApiV1SystemUsersUserIdDisablePostData,
    ThrowOnError
  >,
): RequestResult<
  DisableUserApiV1SystemUsersUserIdDisablePostResponses,
  DisableUserApiV1SystemUsersUserIdDisablePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DisableUserApiV1SystemUsersUserIdDisablePostResponses,
    DisableUserApiV1SystemUsersUserIdDisablePostErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users/{user_id}/disable", ...options });

/**
 * Enable User
 */
export const enableUserApiV1SystemUsersUserIdEnablePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    EnableUserApiV1SystemUsersUserIdEnablePostData,
    ThrowOnError
  >,
): RequestResult<
  EnableUserApiV1SystemUsersUserIdEnablePostResponses,
  EnableUserApiV1SystemUsersUserIdEnablePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    EnableUserApiV1SystemUsersUserIdEnablePostResponses,
    EnableUserApiV1SystemUsersUserIdEnablePostErrors,
    ThrowOnError
  >({ url: "/api/v1/system/users/{user_id}/enable", ...options });

/**
 * Reset Password
 */
export const resetPasswordApiV1SystemUsersUserIdResetPasswordPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ResetPasswordApiV1SystemUsersUserIdResetPasswordPostData,
    ThrowOnError
  >,
): RequestResult<
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses,
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses,
    ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/system/users/{user_id}/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
