// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AuditEntryResponse
 */
export type AuditEntryResponse = {
  /**
   * Action
   */
  action: string;
  /**
   * Actor User Id
   */
  actor_user_id: string | null;
  /**
   * Changes
   */
  changes: {
    [key: string]: unknown;
  };
  /**
   * Created At
   */
  created_at: string;
  /**
   * Id
   */
  id: string;
  /**
   * Object Id
   */
  object_id: string | null;
  /**
   * Object Type
   */
  object_type: string;
  /**
   * Project Id
   */
  project_id: string | null;
  /**
   * Source Ip
   */
  source_ip: string | null;
};

/**
 * AuditListResponse
 */
export type AuditListResponse = {
  /**
   * Items
   */
  items: Array<AuditEntryResponse>;
};

/**
 * CreateProjectRequest
 */
export type CreateProjectRequest = {
  /**
   * Name
   */
  name: string;
};

/**
 * CreateUserRequest
 */
export type CreateUserRequest = {
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Initial Password
   */
  initial_password: string;
  role: SystemRole;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
  /**
   * Service
   */
  service?: "control-api";
  /**
   * Status
   */
  status?: "ok";
  /**
   * Version
   */
  version?: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * ProjectListResponse
 */
export type ProjectListResponse = {
  /**
   * Items
   */
  items: Array<ProjectResponse>;
};

/**
 * ProjectMemberRequest
 */
export type ProjectMemberRequest = {
  role: ProjectMemberRole;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * ProjectMemberResponse
 */
export type ProjectMemberResponse = {
  role: ProjectMemberRole;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * ProjectMemberRole
 */
export type ProjectMemberRole = "developer" | "tester" | "reviewer" | "viewer";

/**
 * ProjectMemberUpdateRequest
 */
export type ProjectMemberUpdateRequest = {
  role: ProjectMemberRole;
};

/**
 * ProjectMembersResponse
 */
export type ProjectMembersResponse = {
  /**
   * Items
   */
  items: Array<ProjectMemberResponse>;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
  /**
   * Archived
   */
  archived: boolean;
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
};

/**
 * RenameProjectRequest
 */
export type RenameProjectRequest = {
  /**
   * Name
   */
  name: string;
};

/**
 * ResetPasswordRequest
 */
export type ResetPasswordRequest = {
  /**
   * New Password
   */
  new_password: string;
};

/**
 * SystemRole
 */
export type SystemRole =
  | "super_admin"
  | "developer"
  | "tester"
  | "reviewer"
  | "viewer";

/**
 * UpdateUserRequest
 */
export type UpdateUserRequest = {
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Email
   */
  email: string;
  role?: SystemRole | null;
};

/**
 * UserPageResponse
 */
export type UserPageResponse = {
  /**
   * Items
   */
  items: Array<UserResponse>;
  /**
   * Next Cursor
   */
  next_cursor: string | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Id
   */
  id: string;
  /**
   * Must Change Password
   */
  must_change_password: boolean;
  role: SystemRole;
  status: UserStatus;
};

/**
 * UserStatus
 */
export type UserStatus = "active" | "disabled";

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
  /**
   * Input
   */
  input?: unknown;
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type LoginApiV1AuthLoginPostData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type LoginApiV1AuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError =
  LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type LoginApiV1AuthLoginPostResponse =
  LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
  body?: never;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type LogoutApiV1AuthLogoutPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError =
  LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type LogoutApiV1AuthLogoutPostResponse =
  LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type CurrentUserApiV1AuthMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type CurrentUserApiV1AuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type CurrentUserApiV1AuthMeGetResponse =
  CurrentUserApiV1AuthMeGetResponses[keyof CurrentUserApiV1AuthMeGetResponses];

export type HealthApiV1HealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/health";
};

export type HealthApiV1HealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type HealthApiV1HealthGetResponse =
  HealthApiV1HealthGetResponses[keyof HealthApiV1HealthGetResponses];

export type ListProjectsApiV1ProjectsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/projects";
};

export type ListProjectsApiV1ProjectsGetResponses = {
  /**
   * Successful Response
   */
  200: ProjectListResponse;
};

export type ListProjectsApiV1ProjectsGetResponse =
  ListProjectsApiV1ProjectsGetResponses[keyof ListProjectsApiV1ProjectsGetResponses];

export type CreateProjectApiV1ProjectsPostData = {
  body: CreateProjectRequest;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path?: never;
  query?: never;
  url: "/api/v1/projects";
};

export type CreateProjectApiV1ProjectsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateProjectApiV1ProjectsPostError =
  CreateProjectApiV1ProjectsPostErrors[keyof CreateProjectApiV1ProjectsPostErrors];

export type CreateProjectApiV1ProjectsPostResponses = {
  /**
   * Successful Response
   */
  201: ProjectResponse;
};

export type CreateProjectApiV1ProjectsPostResponse =
  CreateProjectApiV1ProjectsPostResponses[keyof CreateProjectApiV1ProjectsPostResponses];

export type GetProjectApiV1ProjectsProjectIdGetData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/api/v1/projects/{project_id}";
};

export type GetProjectApiV1ProjectsProjectIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProjectApiV1ProjectsProjectIdGetError =
  GetProjectApiV1ProjectsProjectIdGetErrors[keyof GetProjectApiV1ProjectsProjectIdGetErrors];

export type GetProjectApiV1ProjectsProjectIdGetResponses = {
  /**
   * Successful Response
   */
  200: ProjectResponse;
};

export type GetProjectApiV1ProjectsProjectIdGetResponse =
  GetProjectApiV1ProjectsProjectIdGetResponses[keyof GetProjectApiV1ProjectsProjectIdGetResponses];

export type RenameProjectApiV1ProjectsProjectIdPatchData = {
  body: RenameProjectRequest;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/api/v1/projects/{project_id}";
};

export type RenameProjectApiV1ProjectsProjectIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RenameProjectApiV1ProjectsProjectIdPatchError =
  RenameProjectApiV1ProjectsProjectIdPatchErrors[keyof RenameProjectApiV1ProjectsProjectIdPatchErrors];

export type RenameProjectApiV1ProjectsProjectIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ProjectResponse;
};

export type RenameProjectApiV1ProjectsProjectIdPatchResponse =
  RenameProjectApiV1ProjectsProjectIdPatchResponses[keyof RenameProjectApiV1ProjectsProjectIdPatchResponses];

export type ArchiveProjectApiV1ProjectsProjectIdArchivePostData = {
  body?: never;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/api/v1/projects/{project_id}/archive";
};

export type ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ArchiveProjectApiV1ProjectsProjectIdArchivePostError =
  ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors[keyof ArchiveProjectApiV1ProjectsProjectIdArchivePostErrors];

export type ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses = {
  /**
   * Successful Response
   */
  200: ProjectResponse;
};

export type ArchiveProjectApiV1ProjectsProjectIdArchivePostResponse =
  ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses[keyof ArchiveProjectApiV1ProjectsProjectIdArchivePostResponses];

export type ProjectAuditApiV1ProjectsProjectIdAuditGetData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/projects/{project_id}/audit";
};

export type ProjectAuditApiV1ProjectsProjectIdAuditGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProjectAuditApiV1ProjectsProjectIdAuditGetError =
  ProjectAuditApiV1ProjectsProjectIdAuditGetErrors[keyof ProjectAuditApiV1ProjectsProjectIdAuditGetErrors];

export type ProjectAuditApiV1ProjectsProjectIdAuditGetResponses = {
  /**
   * Successful Response
   */
  200: AuditListResponse;
};

export type ProjectAuditApiV1ProjectsProjectIdAuditGetResponse =
  ProjectAuditApiV1ProjectsProjectIdAuditGetResponses[keyof ProjectAuditApiV1ProjectsProjectIdAuditGetResponses];

export type ListMembersApiV1ProjectsProjectIdMembersGetData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/api/v1/projects/{project_id}/members";
};

export type ListMembersApiV1ProjectsProjectIdMembersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListMembersApiV1ProjectsProjectIdMembersGetError =
  ListMembersApiV1ProjectsProjectIdMembersGetErrors[keyof ListMembersApiV1ProjectsProjectIdMembersGetErrors];

export type ListMembersApiV1ProjectsProjectIdMembersGetResponses = {
  /**
   * Successful Response
   */
  200: ProjectMembersResponse;
};

export type ListMembersApiV1ProjectsProjectIdMembersGetResponse =
  ListMembersApiV1ProjectsProjectIdMembersGetResponses[keyof ListMembersApiV1ProjectsProjectIdMembersGetResponses];

export type AddMemberApiV1ProjectsProjectIdMembersPostData = {
  body: ProjectMemberRequest;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/api/v1/projects/{project_id}/members";
};

export type AddMemberApiV1ProjectsProjectIdMembersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddMemberApiV1ProjectsProjectIdMembersPostError =
  AddMemberApiV1ProjectsProjectIdMembersPostErrors[keyof AddMemberApiV1ProjectsProjectIdMembersPostErrors];

export type AddMemberApiV1ProjectsProjectIdMembersPostResponses = {
  /**
   * Successful Response
   */
  200: ProjectMembersResponse;
};

export type AddMemberApiV1ProjectsProjectIdMembersPostResponse =
  AddMemberApiV1ProjectsProjectIdMembersPostResponses[keyof AddMemberApiV1ProjectsProjectIdMembersPostResponses];

export type RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteData = {
  body?: never;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/projects/{project_id}/members/{user_id}";
};

export type RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteError =
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors[keyof RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteErrors];

export type RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponse =
  RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses[keyof RemoveMemberApiV1ProjectsProjectIdMembersUserIdDeleteResponses];

export type UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchData = {
  body: ProjectMemberUpdateRequest;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/projects/{project_id}/members/{user_id}";
};

export type UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchError =
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors[keyof UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchErrors];

export type UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ProjectMembersResponse;
};

export type UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponse =
  UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses[keyof UpdateMemberApiV1ProjectsProjectIdMembersUserIdPatchResponses];

export type GlobalAuditApiV1SystemAuditGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/system/audit";
};

export type GlobalAuditApiV1SystemAuditGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GlobalAuditApiV1SystemAuditGetError =
  GlobalAuditApiV1SystemAuditGetErrors[keyof GlobalAuditApiV1SystemAuditGetErrors];

export type GlobalAuditApiV1SystemAuditGetResponses = {
  /**
   * Successful Response
   */
  200: AuditListResponse;
};

export type GlobalAuditApiV1SystemAuditGetResponse =
  GlobalAuditApiV1SystemAuditGetResponses[keyof GlobalAuditApiV1SystemAuditGetResponses];

export type ListUsersApiV1SystemUsersGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/system/users";
};

export type ListUsersApiV1SystemUsersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListUsersApiV1SystemUsersGetError =
  ListUsersApiV1SystemUsersGetErrors[keyof ListUsersApiV1SystemUsersGetErrors];

export type ListUsersApiV1SystemUsersGetResponses = {
  /**
   * Successful Response
   */
  200: UserPageResponse;
};

export type ListUsersApiV1SystemUsersGetResponse =
  ListUsersApiV1SystemUsersGetResponses[keyof ListUsersApiV1SystemUsersGetResponses];

export type CreateUserApiV1SystemUsersPostData = {
  body: CreateUserRequest;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path?: never;
  query?: never;
  url: "/api/v1/system/users";
};

export type CreateUserApiV1SystemUsersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserApiV1SystemUsersPostError =
  CreateUserApiV1SystemUsersPostErrors[keyof CreateUserApiV1SystemUsersPostErrors];

export type CreateUserApiV1SystemUsersPostResponses = {
  /**
   * Successful Response
   */
  201: UserResponse;
};

export type CreateUserApiV1SystemUsersPostResponse =
  CreateUserApiV1SystemUsersPostResponses[keyof CreateUserApiV1SystemUsersPostResponses];

export type DeleteUserApiV1SystemUsersUserIdDeleteData = {
  body?: never;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/system/users/{user_id}";
};

export type DeleteUserApiV1SystemUsersUserIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteUserApiV1SystemUsersUserIdDeleteError =
  DeleteUserApiV1SystemUsersUserIdDeleteErrors[keyof DeleteUserApiV1SystemUsersUserIdDeleteErrors];

export type DeleteUserApiV1SystemUsersUserIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteUserApiV1SystemUsersUserIdDeleteResponse =
  DeleteUserApiV1SystemUsersUserIdDeleteResponses[keyof DeleteUserApiV1SystemUsersUserIdDeleteResponses];

export type GetUserApiV1SystemUsersUserIdGetData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/system/users/{user_id}";
};

export type GetUserApiV1SystemUsersUserIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserApiV1SystemUsersUserIdGetError =
  GetUserApiV1SystemUsersUserIdGetErrors[keyof GetUserApiV1SystemUsersUserIdGetErrors];

export type GetUserApiV1SystemUsersUserIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetUserApiV1SystemUsersUserIdGetResponse =
  GetUserApiV1SystemUsersUserIdGetResponses[keyof GetUserApiV1SystemUsersUserIdGetResponses];

export type UpdateUserApiV1SystemUsersUserIdPatchData = {
  body: UpdateUserRequest;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/system/users/{user_id}";
};

export type UpdateUserApiV1SystemUsersUserIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserApiV1SystemUsersUserIdPatchError =
  UpdateUserApiV1SystemUsersUserIdPatchErrors[keyof UpdateUserApiV1SystemUsersUserIdPatchErrors];

export type UpdateUserApiV1SystemUsersUserIdPatchResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type UpdateUserApiV1SystemUsersUserIdPatchResponse =
  UpdateUserApiV1SystemUsersUserIdPatchResponses[keyof UpdateUserApiV1SystemUsersUserIdPatchResponses];

export type DisableUserApiV1SystemUsersUserIdDisablePostData = {
  body?: never;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/system/users/{user_id}/disable";
};

export type DisableUserApiV1SystemUsersUserIdDisablePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DisableUserApiV1SystemUsersUserIdDisablePostError =
  DisableUserApiV1SystemUsersUserIdDisablePostErrors[keyof DisableUserApiV1SystemUsersUserIdDisablePostErrors];

export type DisableUserApiV1SystemUsersUserIdDisablePostResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type DisableUserApiV1SystemUsersUserIdDisablePostResponse =
  DisableUserApiV1SystemUsersUserIdDisablePostResponses[keyof DisableUserApiV1SystemUsersUserIdDisablePostResponses];

export type EnableUserApiV1SystemUsersUserIdEnablePostData = {
  body?: never;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/system/users/{user_id}/enable";
};

export type EnableUserApiV1SystemUsersUserIdEnablePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EnableUserApiV1SystemUsersUserIdEnablePostError =
  EnableUserApiV1SystemUsersUserIdEnablePostErrors[keyof EnableUserApiV1SystemUsersUserIdEnablePostErrors];

export type EnableUserApiV1SystemUsersUserIdEnablePostResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type EnableUserApiV1SystemUsersUserIdEnablePostResponse =
  EnableUserApiV1SystemUsersUserIdEnablePostResponses[keyof EnableUserApiV1SystemUsersUserIdEnablePostResponses];

export type ResetPasswordApiV1SystemUsersUserIdResetPasswordPostData = {
  body: ResetPasswordRequest;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "x-csrf-token"?: string | null;
  };
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/system/users/{user_id}/reset-password";
};

export type ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetPasswordApiV1SystemUsersUserIdResetPasswordPostError =
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors[keyof ResetPasswordApiV1SystemUsersUserIdResetPasswordPostErrors];

export type ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponse =
  ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses[keyof ResetPasswordApiV1SystemUsersUserIdResetPasswordPostResponses];
